name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  Test:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3

      - name: Run Tests
        run: |
          . (Join-Path "." "Tests/runtests.ps1")

      - name: Test AL-GO Workflows
        if: github.repository_owner == 'microsoft'
        run: |
          . (Join-Path "." "Tests/WorkflowSanitation/WorkflowFileExtensions.Test.ps1")
          . (Join-Path "." "Tests/WorkflowSanitation/WorkflowReferences.Test.ps1")
