name: Collect

run-name: "Collect from [${{ inputs.branch }}] to [${{ github.ref_name }}]"

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch to collect from (default is main)
        required: false
        default: 'main'
      directCommit:
        description: Direct COMMIT (Y/N)
        required: false
        default: "N"

defaults:
  run:
    shell: pwsh

jobs:
  Collect:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3

      - name: CheckUser
        run: |
          $threeMusketeers = @("freddydk", "aholstrup1", "mazhelez")
          if ("$ENV:GITHUB_REPOSITORY" -eq "microsoft/AL-Go" -and "$ENV:GITHUB_ACTOR" -notin $threeMusketeers) {
            Write-Host "::Error::You cannot run deploy and collect in the microsoft/AL-Go repo"
            exit 1
          }

      - name: Collect
        run: |
          $errorActionPreference = "Stop"; $ProgressPreference = "SilentlyContinue"; Set-StrictMode -Version 2.0
          try {
            $token = '${{ Secrets.OrgPAT }}'
            if (!$token) {
              throw "In order to run the Collect workflow, you need a Secret called OrgPAT containing a valid Personal Access Token"
            }
            else {
              $githubOwner = "$ENV:GITHUB_REPOSITORY_OWNER"
              $settings = [ordered]@{
                  "githubOwner" = $githubOwner
                  "actionsRepo" = "AL-Go-Actions"
                  "perTenantExtensionRepo" = "AL-Go-PTE"
                  "appSourceAppRepo" = "AL-Go-AppSource"
                  "branch" = '${{ github.event.inputs.branch }}'
                  "localFolder" = ""
                  "baseFolder" = [System.IO.Path]::GetTempPath()
              }
              $settingsFile = Join-Path $settings.baseFolder "deploy.json"
              $settings | ConvertTo-Json | Set-Content $settingsFile -Encoding UTF8
              . ".\Internal\Collect.ps1" -configName $settingsFile -githubOwner $githubOwner -token $token -directCOMMIT:('${{ github.event.inputs.directCOMMIT }}' -eq 'Y')
            }
          }
          catch {
            Write-Host "::Error::Error deploying repositories. The error was $($_.Exception.Message)"
            exit 1
          }
